# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Hello < Formula
  desc "Hello World CLI"
  homepage "https://github.com/fhaifler/hello"
  version "0.1.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/fhaifler/hello/releases/download/v0.1.1/hello_v0.1.1_darwin_amd64.tar.gz"
      sha256 "c54fdea3b97411a122f092a2100e20d7a605459668ef8ef98c1215192faab2d8"

      def install
        bin.install "hello"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/fhaifler/hello/releases/download/v0.1.1/hello_v0.1.1_darwin_arm64.tar.gz"
      sha256 "9d0de5df57f763d7888d2a1db87e5c852c4b46a437b1f7422135c69a5ea5f7b0"

      def install
        bin.install "hello"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/fhaifler/hello/releases/download/v0.1.1/hello_v0.1.1_linux_arm64.tar.gz"
      sha256 "56bd86a1567c704614b56bb5a4ab9e4daab28c4d75d91579bc05232bf992c4bf"

      def install
        bin.install "hello"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/fhaifler/hello/releases/download/v0.1.1/hello_v0.1.1_linux_amd64.tar.gz"
      sha256 "d67aae36a678a8c3ee36be050ea6a659144379a41a8e25da730deb39b38fa6dd"

      def install
        bin.install "hello"
      end
    end
  end

  def caveats; <<~EOS
    How to use this binary: https://github.com/fhaifler/hello
  EOS
  end

  test do
    system "#{bin}/hello version"
  end
end
